personas.persona.*:
  type: config_entity
  label: 'Persona configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'

